### ISSUE TITLE
Three things need to be corrected

### ISSUE THREAD

**Issue by Carmonn** [gavinlyonsrepo/pic_18F47K42_projects#1]
In the file "pic_18F47K42_projects/projects/OLED_GRAPH/SSD1306OLED.c is missing this inlcude ->
#include "mcc_generated_files/examples/i2c1_master_example.h"

And you need to rename the functions that are in line 758 and 769 in the same "SD1306OLED.c" file ->
line 758
current function=    i2c_writeNBytes(SSD1306_ADDR, data_I2C, 2);
correct function=   I2C2_WriteNBytes(SSD1306_ADDR, data_I2C, 2);

line769
current function=  i2c_writeNBytes(SSD1306_ADDR, data_I2C, 2);
correct function=   I2C2_WriteNBytes(SSD1306_ADDR, data_I2C, 2);

After that everything works perfectly, thanks for sharing your code you have saved me

**Comment by gavinlyonsrepo** [comment]
Hi 

I think this is just different options of  configuration  for I2C in the MCC.

I don't know why you would have to add an include as the SD1306OLED.h file has #include "mcc_generated_files/mcc.h"
in it.
Regarding the other issues, the issue here is I have included the I2CSIMPLE from "Libraries - Foundation services" in MCC resources , (In Addition to the I2C peripheral) i2c_simple_master.h which uses the functions with lower case letters i2c.

**Comment by Carmonn** [comment]
You right thanks for all
